In [1]:
from sklearn.svm import SVR
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
from sklearn import datasets

In [2]:
df = datasets.load_diabetes(as_frame=True).frame

In [3]:
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

In [4]:
df.shape

(442, 11)

In [5]:
X = df.drop("target",axis = 1)
y = df["target"]

In [6]:
X.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 42)

In [8]:
y_train.values.reshape(-1,1)

array([[208.],
       [261.],
       [179.],
       [258.],
       [262.],
       [ 51.],
       [237.],
       [ 71.],
       [139.],
       [268.],
       [ 69.],
       [317.],
       [249.],
       [154.],
       [192.],
       [116.],
       [ 81.],
       [122.],
       [259.],
       [191.],
       [292.],
       [ 55.],
       [107.],
       [210.],
       [ 91.],
       [253.],
       [ 85.],
       [252.],
       [ 59.],
       [ 78.],
       [200.],
       [ 78.],
       [245.],
       [175.],
       [ 42.],
       [127.],
       [ 53.],
       [ 94.],
       [104.],
       [199.],
       [265.],
       [281.],
       [248.],
       [257.],
       [215.],
       [303.],
       [170.],
       [ 59.],
       [277.],
       [209.],
       [138.],
       [198.],
       [124.],
       [ 96.],
       [288.],
       [225.],
       [265.],
       [101.],
       [ 55.],
       [198.],
       [ 51.],
       [252.],
       [ 64.],
       [220.],
       [131.],
       [212.],
       [142.],
       [103.],
       [155.],
       [121.],
       [ 86.],
       [111.],
       [ 65.],
       [131.],
       [ 51.],
       [128.],
       [141.],
       [ 48.],
       [109.],
       [178.],
       [ 88.],
       [ 84.],
       [216.],
       [150.],
       [ 60.],
       [ 96.],
       [190.],
       [ 74.],
       [279.],
       [182.],
       [160.],
       [245.],
       [276.],
       [174.],
       [180.],
       [150.],
       [196.],
       [138.],
       [ 97.],
       [246.],
       [321.],
       [308.],
       [109.],
       [ 69.],
       [182.],
       [258.],
       [161.],
       [178.],
       [214.],
       [ 45.],
       [150.],
       [160.],
       [ 55.],
       [197.],
       [185.],
       [268.],
       [310.],
       [123.],
       [ 68.],
       [ 72.],
       [185.],
       [144.],
       [147.],
       [168.],
       [178.],
       [246.],
       [151.],
       [127.],
       [ 83.],
       [332.],
       [152.],
       [109.],
       [ 90.],
       [ 66.],
       [214.],
       [ 85.],
       [129.],
       [ 89.],
       [259.],
       [229.],
       [200.],
       [ 77.],
       [ 54.],
       [ 31.],
       [109.],
       [206.],
       [144.],
       [118.],
       [ 83.],
       [242.],
       [259.],
       [ 72.],
       [163.],
       [181.],
       [141.],
       [ 71.],
       [137.],
       [195.],
       [179.],
       [102.],
       [131.],
       [ 47.],
       [235.],
       [ 77.],
       [198.],
       [ 93.],
       [162.],
       [225.],
       [275.],
       [183.],
       [306.],
       [ 81.],
       [ 55.],
       [146.],
       [196.],
       [230.],
       [310.],
       [ 40.],
       [135.],
       [346.],
       [ 43.],
       [128.],
       [ 77.],
       [235.],
       [ 49.],
       [ 74.],
       [ 92.],
       [ 84.],
       [263.],
       [144.],
       [142.],
       [341.],
       [115.],
       [158.],
       [273.],
       [ 85.],
       [ 88.],
       [220.],
       [ 39.],
       [ 80.],
       [172.],
       [217.],
       [336.],
       [ 52.],
       [272.],
       [115.],
       [110.],
       [131.],
       [ 71.],
       [275.],
       [118.],
       [ 25.],
       [100.],
       [281.],
       [221.],
       [248.],
       [200.],
       [132.],
       [ 91.],
       [ 67.],
       [202.],
       [ 73.],
       [ 85.],
       [275.],
       [243.],
       [ 66.],
       [293.],
       [236.],
       [243.],
       [ 87.],
       [ 39.],
       [217.],
       [ 92.],
       [296.],
       [292.],
       [142.],
       [ 50.],
       [ 53.],
       [104.],
       [ 75.],
       [120.],
       [142.],
       [143.],
       [ 99.],
       [ 65.],
       [116.],
       [233.],
       [164.],
       [ 95.],
       [ 59.],
       [139.],
       [145.],
       [177.],
       [185.],
       [ 97.],
       [ 42.],
       [201.],
       [241.],
       [ 70.],
       [ 78.],
       [ 49.],
       [103.],
       [ 44.],
       [111.],
       [191.],
       [ 47.],
       [182.],
       [ 58.],
       [155.],
       [151.],
       [ 79.],
       [104.],
       [143.],
       [152.],
       [170.],
       [ 75.],
       [200.],
       [124.],
       [ 91.],
       [ 49.],
       [163.],
       [ 53.],
       [283.],
       [178.],
       [219.],
       [200.],
       [113.],
       [113.],
       [ 63.],
       [114.],
       [126.],
       [274.],
       [ 88.],
       [311.],
       [ 83.],
       [ 71.],
       [134.],
       [244.],
       [ 65.],
       [173.],
       [ 57.],
       [ 68.],
       [141.],
       [270.],
       [134.],
       [202.],
       [148.],
       [ 64.],
       [302.]])

In [9]:
y_scaler = StandardScaler()
y_train_scaled = y_scaler.fit_transform(y_train.values.reshape(-1,1)).ravel()
y_test_scaled = y_scaler.transform(y_test.values.reshape(-1,1)).ravel()

In [10]:
model = SVR()

model.fit(X_train, y_train_scaled)

SVR()

In [11]:
y_test_pred_scaled = model.predict(X_test)
y_train_pred_scaled = model.predict(X_train)

In [12]:
print("train r2: ", r2_score(y_train_scaled,y_train_pred_scaled))
print("test r2: ", r2_score(y_test_scaled, y_test_pred_scaled))

train r2:  0.6596361676267715
test r2:  0.48844443151651895

In [13]:
#Linear 

model = SVR(kernel = "linear")

model.fit(X_train, y_train_scaled)

y_test_pred_scaled = model.predict(X_test)
y_train_pred_scaled = model.predict(X_train)

print("train r2: ", r2_score(y_train_scaled,y_train_pred_scaled))
print("test r2: ", r2_score(y_test_scaled, y_test_pred_scaled))

train r2:  0.45191229982475245
test r2:  0.4433761323833776

In [14]:
#Ploynomial 

model = SVR(kernel = "poly")

model.fit(X_train, y_train_scaled)

y_test_pred_scaled = model.predict(X_test)
y_train_pred_scaled = model.predict(X_train)

print("train r2: ", r2_score(y_train_scaled,y_train_pred_scaled))
print("test r2: ", r2_score(y_test_scaled, y_test_pred_scaled))

train r2:  0.5790920834310538
test r2:  0.24203771038107813

In [15]:
#Sigmoid 

model = SVR(kernel = "sigmoid")

model.fit(X_train, y_train_scaled)

y_test_pred_scaled = model.predict(X_test)
y_train_pred_scaled = model.predict(X_train)

print("train r2: ", r2_score(y_train_scaled,y_train_pred_scaled))
print("test r2: ", r2_score(y_test_scaled, y_test_pred_scaled))

train r2:  -19.721193440731305
test r2:  -15.316808189576822

# Hyperparameter tuning using GridSearchCV

In [16]:
from sklearn.model_selection import GridSearchCV

In [17]:
param_grid = {
    "C": [1,2,5,10,50,100],
    "kernel": ["rbf", "linear"],
    "epsilon": [0.001, 0.1, 0.3, 0.5]
}

In [18]:
svr = SVR()

grid_search = GridSearchCV(svr, param_grid, scoring="r2", cv=5)

grid_search.fit(X_train, y_train_scaled)

GridSearchCV(cv=5, estimator=SVR(),
             param_grid={'C': [1, 2, 5, 10, 50, 100],
                         'epsilon': [0.001, 0.1, 0.3, 0.5],
                         'kernel': ['rbf', 'linear']},
             scoring='r2')

In [19]:
print("best param - ", grid_search.best_params_)

best param -  {'C': 10, 'epsilon': 0.1, 'kernel': 'linear'}

In [20]:
best_model = SVR(kernel = "linear", C = 10, epsilon=0.1)

best_model.fit(X_train, y_train_scaled)

y_test_pred_scaled = best_model.predict(X_test)
y_train_pred_scaled = best_model.predict(X_train)

print("train r2: ", r2_score(y_train_scaled,y_train_pred_scaled))
print("test r2: ", r2_score(y_test_scaled, y_test_pred_scaled))

train r2:  0.5151066486918875
test r2:  0.47444183250401084

In [25]:
from sklearn.svm import LinearSVR

model = LinearSVR(C = 10, epsilon = 0.1, max_iter = 5000)

model.fit(X_train, y_train_scaled)

y_test_pred_scaled = model.predict(X_test)
y_train_pred_scaled = model.predict(X_train)

print("train r2: ", r2_score(y_train_scaled,y_train_pred_scaled))
print("test r2: ", r2_score(y_test_scaled, y_test_pred_scaled))

train r2:  0.5151874940611838
test r2:  0.4750702865918678

In [24]:
from sklearn.svm import LinearSVR
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score

# Scale X
X_scaler = StandardScaler()
X_train_scaled = X_scaler.fit_transform(X_train)
X_test_scaled  = X_scaler.transform(X_test)

model = LinearSVR(
    C=1.0,          # lower C
    epsilon=0.1,
    max_iter=10000
)

model.fit(X_train_scaled, y_train_scaled)

y_train_pred_scaled = model.predict(X_train_scaled)
y_test_pred_scaled  = model.predict(X_test_scaled)

print("train r2:", r2_score(y_train_scaled, y_train_pred_scaled))
print("test r2:", r2_score(y_test_scaled, y_test_pred_scaled))

train r2: 0.5181788828550211
test r2: 0.46642139092261115